spring:
  application:
    name: ghostMessage # 프로젝트 이름

  datasource: # DB 접속 정보
    url: jdbc:postgresql://db:5432/ghost_db
    username: ghost_user # 본인의 DB 계정 ID
    password: 1 # 본인의 DB 계정 PW
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: redis
      port: 6379

  cache:
    type: redis

  jpa:
    hibernate:
      ddl-auto: update # 자바 코드를 바탕으로 테이블을 자동 생성/수정함
    show-sql: true # 실행되는 SQL문을 콘솔창에 보여줌
    properties:
      hibernate:
        format_sql: true # SQL문을 보기 좋게 정렬함
        dialect: org.hibernate.dialect.PostgreSQLDialect # DB에 맞는 언어 설정

  sql:
    init:
      mode: always # data.sql을 항상 실행함
